// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyvc-JAT6_7tS7NUtKp_EPTPyCyLvF3Is',
    appId: '1:605901077736:web:09e3f8f54de841b3be9d5d',
    messagingSenderId: '605901077736',
    projectId: 'reminder-app-744b5',
    authDomain: 'reminder-app-744b5.firebaseapp.com',
    storageBucket: 'reminder-app-744b5.firebasestorage.app',
    measurementId: 'G-CKSHKHS2C8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6OQrS6iXwDkRRoDsnbDFvIg2_rK_fk6E',
    appId: '1:605901077736:android:b80c7b2be745ebb8be9d5d',
    messagingSenderId: '605901077736',
    projectId: 'reminder-app-744b5',
    storageBucket: 'reminder-app-744b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNrumDxlQ2ys4o1rD4nsQgZQVV8Tk5zu4',
    appId: '1:605901077736:ios:aff93ecb86622e10be9d5d',
    messagingSenderId: '605901077736',
    projectId: 'reminder-app-744b5',
    storageBucket: 'reminder-app-744b5.firebasestorage.app',
    iosBundleId: 'com.example.reminderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNrumDxlQ2ys4o1rD4nsQgZQVV8Tk5zu4',
    appId: '1:605901077736:ios:aff93ecb86622e10be9d5d',
    messagingSenderId: '605901077736',
    projectId: 'reminder-app-744b5',
    storageBucket: 'reminder-app-744b5.firebasestorage.app',
    iosBundleId: 'com.example.reminderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyvc-JAT6_7tS7NUtKp_EPTPyCyLvF3Is',
    appId: '1:605901077736:web:a997e43d739ed189be9d5d',
    messagingSenderId: '605901077736',
    projectId: 'reminder-app-744b5',
    authDomain: 'reminder-app-744b5.firebaseapp.com',
    storageBucket: 'reminder-app-744b5.firebasestorage.app',
    measurementId: 'G-LJZK4RZ8RE',
  );
}
